apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: slack-bot
      hasuraService: custom
    name: slack-bot
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: slack-bot
      spec:
        containers:
        - image: hasura/hello-world:latest
          imagePullPolicy: IfNotPresent
          name: slack-bot
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          env:
          - name: SLACK_TOKEN
            value: <your-slack-token>
        securityContext: {}
        terminationGracePeriodSeconds: 0
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: slack-bot
      hasuraService: custom
    name: slack-bot
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: slack-bot
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
